# Unique identifier for your project
sonar.projectKey=AegisVault_1.0

# Name and version displayed in the SonarQube/SonarCloud UI
sonar.projectName=Aegis Vault
sonar.projectVersion=1.0

# Path to the source directories (usually 'src')
sonar.sources=src

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Since this is a Java project, point to your compiled .class files
# (IntelliJ usually puts these in 'out' or 'target')
sonar.java.binaries=out/production